create table posts (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    content TEXT,
    created_at timestamp default current_timestamp not null
);

create table comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    content TEXT not null,
    created_at timestamp default current_timestamp not null,
    constraint fk_comments_posts foreign key (post_id)
        references posts(id)
        on delete cascade
);

create index idx_comments_post_id on comments(post_id);
